[versions]
minSdk = "24"
targetSdk = "33"
versionCode = "1"
versionName = "1.0.0"
compileSdk = "33"

# hilt
hilt="2.44"
hilt-navigation= "1.0.0"

# compose material3
material3="1.1.1"

# navigation
navigation-compose ="2.7.0-alpha01"

# viewModel
androidx-lifecycle= "2.3.1"

coroutine = "1.6.4"
coil = "2.2.2"

# default
androidx-core= "1.7.0"
appcompat="1.6.1"
material = "1.9.0"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
javax-inject = "1"
junit = "4.13.2"

# compose
activity-compose = "1.3.1"
compose = "1.2.0-beta02"
constraintlayout-compose= "1.0.1"

# serialization
kotlin = "1.5.30"
kotlinxSerializationJson = "1.4.1"

lottie-compose = "5.2.0"

#timber
timber = "5.0.1"

#retrofit2
okhttp3 = "4.10.0"
interceptor = "4.9.0"
retrofit = "2.9.0"
retrofitSerialization = "0.8.0"
gson = "2.9.0"

# dataStore
dataStore="1.0.0"

[libraries]
# default
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
appcompat = { group = "androidx.appcompat" ,name="appcompat", version.ref="appcompat"}
android-material = { group = "com.google.android.material", name="material", version.ref="material"}
javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "javax-inject" }
test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

# timber
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

# compose
compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-ui= { group = "androidx.compose.ui", name = "ui", version.ref="compose"}
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics"}
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref="compose" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref="compose"}
compose-material = { group = "androidx.compose.material", name = "material", version.ref="compose"}
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

# compose-material3
material3 = { group = "androidx.compose.material3", name = "material3", version.ref="material3" }
material3-window = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref="material3" }

# lifeCycle
lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
lifecycle-viewmodel= { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
# dataStore
dataStore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "dataStore" }
# hilt
hilt-compile = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt= { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
#navigation
navigation-compose = {group = "androidx.navigation", name="navigation-compose", version.ref="navigation-compose"}
hilt-compose-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation" }
# coil
coil-compose = {group = "io.coil-kt", name="coil-compose", version.ref="coil"}
coil-svg = {group ="io.coil-kt", name="coil-svg", version.ref="coil"}
# lottie
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie-compose" }
# retrofit
retrofit-retrofit = {module = "com.squareup.retrofit2:retrofit", version.ref="retrofit"}
retrofit-retrofit-converter = {group = "com.squareup.retrofit2",name="converter-gson", version.ref="retrofit"}
# retrofit2 serialization
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
retrofit-serialization = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofitSerialization" }
#okhttp3 logging
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }
okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "interceptor" }

[bundles]
default = [
    "core-ktx",
    "appcompat",
    "android-material",
]

compose = [
    "compose",
    "compose-material",
    "compose-ui",
    "compose-ui-graphics",
    "compose-ui-tooling-preview",
    "compose-ui-util",
]

material3 = [
    "material3",
    "material3-window"
]

coil = [
    "coil-compose",
    "coil-svg"
]

lifecycle = [
    "lifecycle-runtime",
    "lifecycle-viewmodel"
]

timber = [
    "timber"
]


network = [
    "retrofit-retrofit",
    "retrofit-retrofit-converter",
    "okhttp3",
    "okhttp3-logging-interceptor"
]

dataStore = ["dataStore"]

retrofitSerialization = [
    "kotlinx-serialization-json",
    "retrofit-serialization"
]
navigation = [
    "hilt-compose-navigation",
    "navigation-compose"
]

lottie = [
    "lottie-compose"
]

